CC = gcc
CFLAGS = -g -Wall -std=cdd -fsanitize=address 

chunk.o: chunk.c chunk.h
	$(CC) $(CFLAGS) chunk.c
	
mymalloc.o: mymalloc.c mymalloc.h
	$(CC) $(CFLAGS) mymalloc.c -o mymalloc

memgrind.o: memgrind.c
	$(CC) $(CFLAGS) memgrind.c -o memgrind

memgrind: memgrind.o freelist.o mymalloc.o chunk.o
	$(CC) $(CFLAGS) memgrind.o mymalloc.o chunk.o -o memgrind